config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',                 via: 'get'
  match '/destroy_profile/:id', to: 'users#destroy', via: 'delete'
  match '/signin',  to: 'sessions#new',              via: 'get'
  match '/signout', to: 'sessions#destroy',          via: 'delete'
  match '/help',    to: 'static_pages#help',         via: 'get'
  match '/about',   to: 'static_pages#about',        via: 'get'
  match '/contact', to: 'static_pages#contact',      via: 'get'
  match '/news',    to: 'static_pages#news',         via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def news
    @feed_items = Micropost.all.paginate(page: params[:page])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <div class="row">
      <aside class="col-sm-4 home-user-nav">
        <div>
          <%= render 'shared/user_info' %>
        </div>
        <div>
          <%= render 'shared/stats' %>
        </div>
        <div>
          <%= render 'shared/micropost_form' %>
        </div>
      </aside>
        <div class="col-sm-7 home-news-feed">
          <h3>Новости</h3>
          <%= render 'shared/feed' %>
        </div>
        </div>
<% else %>
    <div class="logo col-sm-12">
      <%= image_tag 'logo.png', alt: 'logo', width: 500 %><br>
    </div>
    <div class="center hero-unit non-signed-home-div">
      <%= link_to 'Войти', signin_path, class: 'sign-in-link' %><br>
      <p>или</p>
      <%= link_to 'Зарегистрироваться', signup_path, class: 'sign-out-link' %>
    </div>
<% end %>

app/views/static_pages/news.html.erb
<%= render partial: 'shared/feed' %>