config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',                 via: 'get'
  match '/destroy_profile/:id', to: 'users#destroy', via: 'delete'
  match '/signin',  to: 'sessions#new',              via: 'get'
  match '/signout', to: 'sessions#destroy',          via: 'delete'
  match '/help',    to: 'static_pages#help',         via: 'get'
  match '/about',   to: 'static_pages#about',        via: 'get'
  match '/contact', to: 'static_pages#contact',      via: 'get'
  match '/news',    to: 'static_pages#news',         via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<% if signed_in? %>
<header>
    <div class="col-sm-3 nav-upper-left">
      <ul>
        <li><%= link_to image_tag(current_user.avatar.url(:thumb)), user_path(current_user) %></li>
        <li>
          <%= link_to current_user.name, user_path(current_user) %>
          <p><%= current_user.group %></p>
        </li>
      </ul>
    </div>
    <div class="nav-upper-right">
      <ul>
        <li><%= link_to image_tag('home.png', alt: 'home page'), root_path %></li>
        <li><%= link_to image_tag('friends.png', alt: 'profile page'), users_path %></li>
        <li><%= link_to image_tag('news.png', alt: 'news page'), '/news' %></li>
        <li><%= link_to image_tag('settings.png', alt: 'accout settings'),
                        "/users/#{current_user.id}/edit" %></li>
        <li><%= link_to image_tag('door.png', alt: 'exit', width: 60), signout_path, method: 'delete' %></li>
      </ul>
    </div>
</header>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</div>
</body>
</html>